# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False)),
                ('value', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('start', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('detail_url', models.URLField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'ordering': ('-start',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=200)),
                ('slug', models.CharField(db_index=True, max_length=200, unique=True)),
                ('verbose_name', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('default_value', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('required_value', models.BooleanField(default=True)),
                ('value_type', models.CharField(blank=True, choices=[('integer', 'integer')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('display_template', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_templates', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='EventConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='events.EventConfig'),
        ),
    ]
